config/routes.rb
Rails.application.routes.draw do
  devise_for :admins


  resources :catalog, controller: 'base_goods_descriptions'
  resources :goods,   except: [:show]
  resources :images,  only: [:destroy]

  resource :cart, only: [:show] do
    put 'add/:id',    to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  resources :orders do
    get 'status'
    put 'status', to: 'orders#change'
  end

  get 'delivery'  => 'pages#show', page: 'delivery'
  get 'payment'   => 'pages#show', page: 'payment'
  get 'contacts'  => 'pages#show', page: 'contacts'

  root :to => 'base_goods_descriptions#index'

  # all unknown request match to 404 via Pages controller
  match '*path' => 'pages#show', via: :all
end

app/models/base_goods_description.rb
class BaseGoodsDescription < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :goods,  :dependent => :destroy
  has_many :images, :dependent => :destroy

  def in_hand
    self[:in_hand] ? 'Да' : 'Нет'
  end

  def total_colors
    Good.where(:base_goods_description_id => self.id).count
  end
end

app/controllers/base_goods_descriptions_controller.rb
class BaseGoodsDescriptionsController < ApplicationController
  before_action :set_base_goods_description,  only:   [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!,         except: [:show, :index]
  before_action :setup_cart,                  only:   [:show]

  # GET /base_goods_descriptions
  def index
    @base_goods_descriptions = BaseGoodsDescription.all.order(:id)
  end

  # GET /base_goods_descriptions/1
  def show
    @goods  = @base_goods_description.goods.order(:color)
    @images = @base_goods_description.images
  end

  # GET /base_goods_descriptions/new
  def new
    @base_goods_description = BaseGoodsDescription.new
  end

  # GET /base_goods_descriptions/1/edit
  def edit
    @images = @base_goods_description.images
  end

  # POST /base_goods_descriptions
  def create
    @base_goods_description = BaseGoodsDescription.new(base_goods_description_params)

    if @base_goods_description.save
      if params[:images]
        #===== The magic is here ;)
        params[:images].each do |image|
          @base_goods_description.images.create(image: image)
        end
      end
      redirect_to catalog_path(@base_goods_description), notice: 'Базовое описание товара создано.'

    else
      render :new
    end
  end

  # PATCH/PUT /base_goods_descriptions/1
  def update
      if @base_goods_description.update(base_goods_description_params)
        if params[:images]
          #===== The magic is here ;)
          params[:images].each do |image|
            @base_goods_description.images.create(image: image)
          end
        end

        redirect_to catalog_path(@base_goods_description), notice: 'Базовое описание товара изменено.'
      else
        render :edit
      end
  end

  # DELETE /base_goods_descriptions/1
  def destroy
    @base_goods_description.destroy
    redirect_to catalog_index_path, notice: 'Базовое описание товара удалено.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_goods_description
      @base_goods_description = BaseGoodsDescription.friendly.find(params[:id])
    end

    def setup_cart
      @cart_hash = if cookies.signed[:cart]
        JSON.parse(cookies.signed[:cart])
      else
        Hash.new
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_goods_description_params
      params.require(:base_goods_description).permit(:name, :description, :country, :youtube_link, :in_hand, :base, :burning_time, :height, :cost, :diameter)
    end
end

app/views/base_goods_descriptions/_form.html.slim
= form_for @base_goods_description, url: catalog_path(@base_goods_description), :html => { :multipart => true } do |f|
  - if @base_goods_description.errors.any?
    #error_explanation
      h2 = "#{pluralize(@base_goods_description.errors.count, "error")} prohibited this base_goods_description from being saved:"
      ul
        - @base_goods_description.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, 'Название'
    = f.text_field :name
  .field
    = f.label :description, 'Описание'
    = f.text_area :description, rows: 4
  .field
    = f.label :cost, 'Цена'
    = f.number_field :cost
  .field
    = f.label :country, 'Страна'
    = f.text_field :country
  .field
    = f.label :youtube_link, 'Youtube-видео'
    = f.text_field :youtube_link
  .field
    = f.label :in_hand, 'В руке'
    = f.check_box :in_hand
  .field
    = f.label :base, 'Основание'
    = f.text_field :base
  .field
    = f.label :burning_time, 'Время горения'
    = f.number_field :burning_time
  .field
    = f.label :height, 'Высота'
    = f.number_field :height
  .field
    = f.label :diameter, 'Диаметр'
    = f.number_field :diameter
  .field
    - unless @images.empty?
      ul.no-bullet
        - @images.each do |img|
          li
            => image_tag img.image.url(:small)
            = link_to ( fa_icon 'remove', text: 'Удалить картинку'), img,
                      :data => { :remote => true },
                      :method => :delete
    = file_field_tag "images[]", type: :file, multiple: true
  .actions = f.submit 'Сохранить', :class => 'button success expanded'

app/views/base_goods_descriptions/edit.html.slim
.row.column
  h1.text-center.subheader Редактирование базового описания товара

  == render 'form'

app/views/base_goods_descriptions/index.html.slim
.cover
  #mobile-cover.show-for-small-only
  video.hide-for-small-only playsinline='' autoplay='' muted='' loop='' poster=asset_path('squares_bg.png')
    source src=asset_path(rand(1..6).to_s + '.mp4') type='video/mp4'
  .row.column.text-center
      = image_tag 'smoke.svg', class: 'puk'
      h1 Цветной дым
      p.lead
        |Оригинальное решение для незабываемой фотосессии, свадьбы или другого мероприятия.
        br
        |Только у нас — самый широкий выбор цветов!

      #scroll-down = fa_icon 'arrow-down 3x'

.cover-main
  .row.small-up-1.large-up-3
    - @base_goods_descriptions.each do |base_goods_description|
      .column.text-center
        .card
          = link_to catalog_path(base_goods_description)
            .card-section
              h2.text-center = base_goods_description.name
              p
                'Время горения:
                strong => base_goods_description.burning_time
                |секунд
                br
                'Всего цветов:
                strong = base_goods_description.total_colors
                br
                = base_goods_description.country

              .stat
                => base_goods_description.cost
                |&#x20bd;
            .card-section = image_tag "#{base_goods_description.id}.jpg", title: base_goods_description.name, alt: base_goods_description.name

css:
  #preloader>p{display:none;}#preloader_preload{display: block;position: fixed;z-index: 99999;top: 0;left: 0;width: 100%;height: 100%;min-width: 1000px;background: #DB0A5B url("#{asset_path('preloader.svg')}") center center no-repeat;background-size:41px;}

#preloader: #preloader_preload

javascript:
  var preloader = document.getElementById('preloader_preload');

  function fadeOutnojquery(el) {
    el.style.opacity = 1;
    var interpreloader = setInterval(function(){
      el.style.opacity = el.style.opacity - 0.05;
      if (el.style.opacity <= 0.05){
        clearInterval(interpreloader);
        preloader.style.display = "none";
      }
    }, 16);
  }

  window.onload = function () {
    setTimeout( function() {
      fadeOutnojquery(preloader);
    }, 0);
  };

  $(document).ready( function () {
    $cover_height = $( window ).height() - 24;

    $('.cover').height ( $cover_height );

    $('#scroll-down').click( function () {
      $('html, body').animate({
        scrollTop: $('.cover-main').offset().top
      }, 2000);
    } );
  } );

app/views/base_goods_descriptions/new.html.slim
.row.column
  h1 Новое базовое описание товара

  == render 'form'

  = link_to (fa_icon 'arrow-left', text: 'Назад'), base_goods_descriptions_path

app/views/base_goods_descriptions/show.html.slim
= javascript_include_tag 'base_goods_descriptions.js'
= content_for :title, 'Цветной дым ' + @base_goods_description.name

.row
  .medium-12.columns
    h1.text-center = @base_goods_description.name
    .row
      .medium-7.medium-centered.small-12.columns
        .row.small-up-2.medium-up-4.text-center
          .column.column-block
            | Цена
            .stat
              => @base_goods_description.cost
              |&#x20bd;
          .column.column-block
            | Всего цветов
            .stat = @base_goods_description.total_colors
          .column.column-block
            | Время горения
            .stat
              => @base_goods_description.burning_time
              |с
          .column.column-block
            | Видео
            .stat: a href='#' data-open='youtube' = fa_icon 'youtube'

      .medium-12.columns.text-center
        p.lead = @base_goods_description.description

    .row
      .medium-6.columns = image_tag("#{@base_goods_description.id}.jpg")
      .medium-3.columns.medium-push-3
        ul.no-bullet
          li
            'Страна производства:
            strong = @base_goods_description.country
          li
            'В руке:
            strong = @base_goods_description.in_hand

          - if @base_goods_description.base.present?
            li
              'Основа:
              strong = @base_goods_description.base
          li
            'Высота:
            strong #{@base_goods_description.height} см
          li
            'Диаметр:
            strong #{@base_goods_description.diameter} см
      .medium-3.columns.medium-pull-3
        ul.no-bullet
          - @goods.each do |g|
            li.clearfix
              .float-left
                svg.g-color> xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" width="14px" height="14px"
                  defs
                    style .cls-#{g.id}{fill:#{g[:color_code]};}
                  circle class="cls-#{g.id}" cx="9" cy="9" r="9"
                = g[:color]

              .float-right.button-group.tiny data-id=g.id
                - if g.available > 0
                  = link_to remove_from_cart_path(g), method: :put, remote: true, class: 'remove button hide', :'data-id' => g.id
                    = fa_icon 'minus'
                  strong.button.hollow.tiny.quantity.hide<> data-id=g.id = @cart_hash[g.id.to_s]
                  = link_to 'В корзину', add_to_cart_path(g), method: :put, remote: true, class: 'button add', :'data-id' => g.id
                  = link_to 'Заказать', cart_path, class: 'checkout button hollow hide', :'data-id' => g.id

                  - if @cart_hash[g.id.to_s] && @cart_hash[g.id.to_s] > 0
                    javascript:
                      $(document).ready(function() {
                        $('[data-id="#{g.id}"] .add').html('<i class="fa fa-plus"></i>');
                        $('[data-id="#{g.id}"] .checkout').removeClass('hide');
                        $('[data-id="#{g.id}"] .quantity').removeClass('hide');
                        $('[data-id="#{g.id}"] .remove').removeClass('hide');
                      });

                - else
                  .button.hollow.disabled.tiny.alert Нет в наличии


    .row.column
      - unless @images.empty?
        .magnific
          - @images.each do |img|
            => link_to img.image.url(:large), class: 'thumbnail'
              = image_tag img.image.url(:small)

.reveal.large#youtube(data-reveal)
  h4 = @base_goods_description.name
  .responsive-embed.widescreen.video-container.flex-video
    #player
  button.close-button type='button' data-close='' &times;

javascript:
  var player;

  $(window).on(
    'open.zf.reveal', function () {
      player = new YT.Player('player', {
                              height: '100%',
                              width: '100%',
                              videoId: "#{@base_goods_description.youtube_link}",
                              events: {
                                'onReady': onPlayerReady,
                                'onStateChange': onPlayerStateChange
                              }
                            });

      function onPlayerReady(event) {
        event.target.playVideo();
      }

      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          done = true;
        }
      }

      function stopVideo() {
        player.stopVideo();
      }
    }
  );

  $(window).on(
    'closed.zf.reveal', function () {
      player.stopVideo();
      $('#youtube .flex-video #player').remove();
      $('#youtube .flex-video').append('<div id="player" />');
    }
  );

  $(document).ready( function () {
    $('.magnific').magnificPopup ( {
    delegate: 'a', // child items selector, by clicking on it popup will open
    type: 'image',
    gallery: {
      enabled: true
    }
    // other options
    } );
  } );