config/routes.rb
Rails.application.routes.draw do
  devise_for :admins


  resources :catalog, controller: 'base_goods_descriptions'
  resources :goods,   except: [:show]
  resources :images,  only: [:destroy]

  resource :cart, only: [:show] do
    put 'add/:id',    to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  resources :orders do
    get 'status'
    put 'status', to: 'orders#change'
  end

  get 'delivery'  => 'pages#show', page: 'delivery'
  get 'payment'   => 'pages#show', page: 'payment'
  get 'contacts'  => 'pages#show', page: 'contacts'

  root :to => 'base_goods_descriptions#index'

  # all unknown request match to 404 via Pages controller
  match '*path' => 'pages#show', via: :all
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :base_goods_description

  def available
    self[:quantity] - Reserve.where(:good_id => self[:id]).sum(:quantity)
  end

  def reserved
    Reserve.where(:good_id => self[:id]).sum(:quantity)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_good, only: [:edit, :update, :destroy]
  before_action :set_base_good_descriptions, only: [:new, :edit]

  # GET /goods
  def index
    @goods = Good.all.order(:id)
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  def create
    @good = Good.new(good_params)

    if @good.save
      redirect_to goods_url, notice: 'Товар создан.'
    else
      format.html { render :new }
    end
  end

  # PATCH/PUT /goods/1
  def update
    if @good.update(good_params)
      redirect_to goods_url, notice: 'Товар изменен.'
    else
      render :edit
    end
  end

  # DELETE /goods/1
  def destroy
    @good.destroy

    redirect_to goods_url, notice: 'Товар удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    def set_base_good_descriptions
      @base_goods_descriptions_array = BaseGoodsDescription.all.map { |bgd| [bgd.name, bgd.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.fetch(:good, {}).permit(:quantity, :color, :color_code)
    end
end

app/views/goods/_form.html.slim
= form_for @good do |f|
  - if @good.errors.any?
    #error_explanation
      h2 = "#{pluralize(@good.errors.count, "error")} prohibited this good from being saved:"
      ul
        - @good.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :base_goods_description_id, 'Базовый товар'
    = select_tag(:base_goods_description_id, options_for_select(@base_goods_descriptions_array))

  .field
    = f.label :color, 'Цвет (название)'
    = f.text_field :color

  .field
    = f.label :color_code, 'Цвет (код HTML)'
    = f.text_field :color_code

  .field
    = f.label :quantity, 'Количество на складе'
    = f.number_field :quantity

  = f.submit 'Сохранить', class: 'button success expanded'

.float-left = link_to (fa_icon 'arrow-left', text: 'Назад'), goods_path, class: 'button hollow secondary'

javascript:
  $(document).ready(function() {
    $('input[type=text]#good_color_code').minicolors( {
      theme: 'bootstrap'
    } );
  } );

app/views/goods/edit.html.slim
.row.column.clearfix
  h1
    small.subheader Редактирование товара
    =< @good.base_goods_description.name
    =< @good.color

  == render 'form'

  .float-right  = link_to (fa_icon 'remove', text: 'Удалить'), @good, data: { confirm: 'Вы уверены?' }, method: :delete, class: 'button alert'

app/views/goods/index.html.slim
= javascript_include_tag 'datatables.js'

.row.column
  br
  = link_to (fa_icon 'plus', text: 'Добавить товар'), new_good_path, class: 'button'

  table#goods
    thead
      tr
        th Название
        th На складе
        th Резерв

    tbody
      - @goods.each do |good|
        tr data-href=edit_good_path(good)
          td = good.base_goods_description.name + ' ' + good.color
          td.text-right = good.quantity
          td.text-right = good.reserved

javascript:
  $(document).ready(function() {
    $('#goods').DataTable( {
      "language": {
        "processing": "Подождите...",
        "search": "Поиск:",
        "lengthMenu": "Показать _MENU_ записей",
        "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
        "infoEmpty": "Записи с 0 по 0 из 0 записей",
        "infoFiltered": "(отфильтровано из _MAX_ записей)",
        "infoPostFix": "",
        "loadingRecords": "Загрузка записей...",
        "zeroRecords": "Записи отсутствуют.",
        "emptyTable": "В таблице отсутствуют данные",
        "paginate": {
          "first": "Первая",
          "previous": "Предыдущая",
          "next": "Следующая",
          "last": "Последняя"
        },
        "aria": {
          "sortAscending": ": активировать для сортировки столбца по возрастанию",
          "sortDescending": ": активировать для сортировки столбца по убыванию"
        }
      },
    } );
  } );

app/views/goods/new.html.slim
.row.column.clearfix
  h1 Новый товар

  == render 'form'